title: Training Tracker
description: Documentation and Resources
markdown: kramdown
show_downloads: true
github:
  zip_url: https://github.com/ICS496-Training-Tracker/ICS496-Training-Tracker/zipball/main
  tar_url: https://github.com/ICS496-Training-Tracker/ICS496-Training-Tracker/tarball/main
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
